### ISSUE TITLE
edge matrix contains doubles

### ISSUE THREAD

**Issue by KlausVigo** [fmichonneau/rncl#17]
Dear @fmichonneau , 
I realized that rncl contains a major undocumented feature (bug?!?). The elements in the edge matrix are stored as double and not as integer. This requires more memory and comparisons like 'which(edge==1L)' are dangerous. I really had hard time finding a bug caused by double matrix once, it is extremely rare but it can happen. Also some function in phangorn would expect integers (I know I am selfish).
Cheers, 
Klaus

**Comment by fmichonneau** [comment]
Thanks for the report @KlausVigo . Yes, that needs to be fixed!
I'm currently working on preparing a new release, and I'm going to look into it.

**Comment by fmichonneau** [comment]
thanks for pointing this out, it's fixed on github now. I'll probably release a new version to CRAN in the next few days.
